/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 sophia.glb -T 
Files: sophia.glb [8.15MB] > C:\Users\sahar\OneDrive\Desktop\New folder (2)\logistics-remix\New folder\rrojexc\public\Sophias\sophia-transformed.glb [599.07KB] (93%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Sophia(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/public/models/sophia.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.rp_sophia_animated_003_idling_root} />
        </group>
        <skinnedMesh name="rp_sophia_animated_003_idling_geo" geometry={nodes.rp_sophia_animated_003_idling_geo.geometry} material={materials.rp_sophia_animated_003_mat} skeleton={nodes.rp_sophia_animated_003_idling_geo.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      </group>
    </group>
  )
}

useGLTF.preload('/public/models/sophia.glb')
